module reload
     use parameters
     use vars
     use hdf5
	 INTEGER(HID_T) :: h5real_psn
contains 
	
	 subroutine RestartMPI
         write(str1,'(I0)') restart_time
         write(str2,'(I0)') proc
         fname=trim(data_folder)//"/restart"//"/param_"//trim(str2)//"_"//trim(str1)
         data_dim1(1)=1
		 call h5open_f(err)
         call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)
         call h5dopen_f(fid,'lproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,lproc,data_dim1,err)
         call h5dopen_f(fid,'rproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,rproc,data_dim1,err)
         call h5dopen_f(fid,'tproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,tproc,data_dim1,err)
         call h5dopen_f(fid,'bproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,bproc,data_dim1,err)
         call h5dopen_f(fid,'uproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,uproc,data_dim1,err)
         call h5dopen_f(fid,'dproc', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,dproc,data_dim1,err)
		 call h5fclose_f(fid,err)
         call h5close_f(err)
	 end subroutine RestartMPI 
     subroutine RestartInitParam
          write(str1,'(I0)') restart_time
          write(str2,'(I0)') proc
          fname=trim(data_folder)//"/restart"//"/param_"//trim(str2)//"_"//trim(str1)
          data_dim1(1)=1
          call h5open_f(err)
          call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)
          call h5dopen_f(fid,'mx', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,mx,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'my', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,my,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'mz', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,mz,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'prtl_arr_size', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,prtl_arr_size,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'test_prtl_arr_size', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,test_prtl_arr_size,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'used_prtl_arr_size', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,used_prtl_arr_size,data_dim1,err)
          call h5dclose_f(dset_id,err)  
          call h5dopen_f(fid,'used_test_prtl_arr_size', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,used_test_prtl_arr_size,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'np', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,np,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'ntp', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,ntp,data_dim1,err)
          call h5dclose_f(dset_id,err) 

          tstart=restart_time+1
          allocate(qp(prtl_arr_size))
          allocate(xp(prtl_arr_size)) 
          allocate(yp(prtl_arr_size)) 
          allocate(zp(prtl_arr_size)) 
          allocate(up(prtl_arr_size)) 
          allocate(vp(prtl_arr_size)) 
          allocate(wp(prtl_arr_size)) 
          allocate(tagp(prtl_arr_size)) 
          allocate(flvp(prtl_arr_size))
          allocate(var1p(prtl_arr_size))
		  
		  
          allocate(qtp(prtl_arr_size))
          allocate(xtp(prtl_arr_size)) 
          allocate(ytp(prtl_arr_size)) 
          allocate(ztp(prtl_arr_size)) 
          allocate(utp(prtl_arr_size)) 
          allocate(vtp(prtl_arr_size)) 
          allocate(wtp(prtl_arr_size)) 
          allocate(tagtp(prtl_arr_size)) 
          allocate(flvtp(prtl_arr_size))
          allocate(var1tp(prtl_arr_size))	  
          
!        call h5dopen_f(fid,'gmin_elc', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_REAL,gmin_elc,data_dim1,err)
!           call h5dclose_f(dset_id,err)
!         call h5dopen_f(fid,'gmax_elc', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_REAL,gmax_elc,data_dim1,err)
!           call h5dclose_f(dset_id,err)
!         call h5dopen_f(fid,'gbin_size_elc', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,gbin_width_elc,data_dim1,err)
!           call h5dclose_f(dset_id,err)
!         call h5dopen_f(fid,'gmin_ion', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_REAL,gmin_ion,data_dim1,err)
!           call h5dclose_f(dset_id,err)
!         call h5dopen_f(fid,'gmax_ion', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_REAL,gmax_ion,data_dim1,err)
!           call h5dclose_f(dset_id,err)
!         call h5dopen_f(fid,'gbin_size_ion', dset_id, err)
!         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,gbin_width_ion,data_dim1,err)
!           call h5dclose_f(dset_id,err)
          call h5fclose_f(fid,err)
          call h5close_f(err)
     end subroutine RestartInitParam
     subroutine RestartInitFlds
          write(str1,'(I0)') restart_time
          write(str2,'(I0)') proc
          fname=trim(data_folder)//"/restart"//"/fld_"//trim(str2)//"_"//trim(str1)
          data_dim3(1)=mx
          data_dim3(2)=my
          data_dim3(3)=mz
		  
          call h5open_f(err)
          select case(psn)
          case(kind(1.0d0))
             call h5tcopy_f(H5T_NATIVE_DOUBLE,h5real_psn,err)
          case(kind(1.0e0))
             call h5tcopy_f(H5T_NATIVE_REAL,h5real_psn,err)
          end select		  
          call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)		  
          call h5dopen_f(fid,'Ex', dset_id, err)		  
          call h5dread_f(dset_id,h5real_psn,Ex,data_dim3,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'Ey', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,Ey,data_dim3,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'Ez', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,Ez,data_dim3,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'Bx', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,Bx,data_dim3,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'By', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,By,data_dim3,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'Bz', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,Bz,data_dim3,err)
          call h5dclose_f(dset_id,err)
 		  call h5fclose_f(fid,err)
          call h5close_f(err)		  
     end subroutine RestartInitFlds
	 
     subroutine RestartInitPrtl
          write(str1,'(I0)') restart_time
          write(str2,'(I0)') proc
          call h5open_f(err)
          select case(psn)
          case(kind(1.0d0))
             call h5tcopy_f(H5T_NATIVE_DOUBLE,h5real_psn,err)
          case(kind(1.0e0))
             call h5tcopy_f(H5T_NATIVE_REAL,h5real_psn,err)
          end select
		  
          fname=trim(data_folder)//"/restart"//"/param_"//trim(str2)//"_"//trim(str1)
          data_dim1(1)=1
          call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)		  	  
          call h5dopen_f(fid,'Nflvr', dset_id, err)		  
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,Nflvr,data_dim1,err)
          call h5dclose_f(dset_id,err) 
		  
          allocate(flvrqm(Nflvr),FlvrSaveFldData(Nflvr),FlvrType(Nflvr),FlvrSplitPrtl(Nflvr))
          allocate(CurrentTagID(Nflvr),TagCounter(Nflvr))
          data_dim1(1)=Nflvr
          call h5dopen_f(fid,'flvrqm', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,flvrqm,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'FlvrSaveFldData', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,FlvrSaveFldData,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'FlvrType', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,FlvrType,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'FlvrSplitPrtl', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,FlvrSplitPrtl,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'CurrentTagID', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,CurrentTagID,data_dim1,err)
          call h5dclose_f(dset_id,err) 
          call h5dopen_f(fid,'TagCounter', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,TagCounter,data_dim1,err)
          call h5dclose_f(dset_id,err) 
		  
		  !Now Load Prtl Data 
          fname=trim(data_folder)//"/restart"//"/prtl_"//trim(str2)//"_"//trim(str1)
          data_dim1(1)=prtl_arr_size
          call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)
          call h5dopen_f(fid,'qp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,qp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'flvp', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,flvp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'tagp', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,tagp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'xp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,xp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'yp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,yp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'zp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,zp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'up', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,up,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'vp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,vp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'wp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,wp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'var1p', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,var1p,data_dim1,err)
          call h5dclose_f(dset_id,err)
 		  
          call h5dopen_f(fid,'qtp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,qtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'flvtp', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,flvtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'tagtp', dset_id, err)
          call h5dread_f(dset_id,H5T_NATIVE_INTEGER,tagtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'xtp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,xtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'ytp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,ytp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'ztp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,ztp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'utp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,utp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'vtp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,vtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'wtp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,wtp,data_dim1,err)
          call h5dclose_f(dset_id,err)
          call h5dopen_f(fid,'var1tp', dset_id, err)
          call h5dread_f(dset_id,h5real_psn,var1tp,data_dim1,err)
          call h5dclose_f(dset_id,err)
		  		  
		  call h5fclose_f(fid,err)
          call h5close_f(err)
     end subroutine RestartInitPrtl
	 
	 subroutine RestartAllVars
         write(str1,'(I0)') restart_time
         write(str2,'(I0)') proc
         fname=trim(data_folder)//"/restart"//"/param_"//trim(str2)//"_"//trim(str1)
         data_dim1(1)=1
         call h5open_f(err)
         call h5fopen_f(fname,H5F_ACC_RDONLY_F,fid, err)
         call h5dopen_f(fid,'xborders', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,xborders,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'yborders', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,yborders,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'zborders', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,zborders,data_dim1,err)
         call h5dclose_f(dset_id,err)
		 print*,'xborders',xborders
		 
         call h5dopen_f(fid,'procxind', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,procxind,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'procyind', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,procyind,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'proczind', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,proczind,data_dim1,err)
         call h5dclose_f(dset_id,err)
		 
         call h5dopen_f(fid,'fdataxi_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdataxi_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'fdataxf_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdataxf_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'fdatayi_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdatayi_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'fdatayf_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdatayf_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'fdatazi_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdatazi_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
         call h5dopen_f(fid,'fdatazf_box', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,fdatazf_box,data_dim1,err)
         call h5dclose_f(dset_id,err)
		 
         data_dim3(3)=3
         call h5dopen_f(fid,'proc_grid', dset_id, err)
         call h5dread_f(dset_id,H5T_NATIVE_INTEGER,proc_grid,data_dim3,err)
         call h5dclose_f(dset_id,err)
		 call h5fclose_f(fid,err)
		 call h5close_f(err)
		 
	 end subroutine RestartAllVars
     
end module reload